// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SRMS.API.Data.AppContext;

#nullable disable

namespace SRMS.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230829131040_002")]
    partial class _002
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SRMS.Shared.Models.Class1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Test")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Class1s");
                });

            modelBuilder.Entity("SRMS.Shared.Models.Level", b =>
                {
                    b.Property<int>("LevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LevelId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LevelName")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.HasKey("LevelId");

                    b.ToTable("Levels");

                    b.HasData(
                        new
                        {
                            LevelId = 1,
                            Description = "Level for basic learners",
                            IsActive = true,
                            LevelName = "Basic"
                        },
                        new
                        {
                            LevelId = 2,
                            Description = "Level for advance learners",
                            IsActive = true,
                            LevelName = "Advance"
                        },
                        new
                        {
                            LevelId = 3,
                            Description = "Level for full level learners",
                            IsActive = true,
                            LevelName = "Full Level"
                        });
                });

            modelBuilder.Entity("SRMS.Shared.Models.Registration", b =>
                {
                    b.Property<int>("RegistrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegistrationId"));

                    b.Property<DateTime?>("DateofBirth")
                        .HasColumnType("Date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("NameInKhmer")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNo")
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("RegistrationDated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sex")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Telegram")
                        .HasColumnType("varchar(50)");

                    b.HasKey("RegistrationId");

                    b.ToTable("Registrations");
                });

            modelBuilder.Entity("SRMS.Shared.Models.RegistrationLine", b =>
                {
                    b.Property<int>("RegistrationLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegistrationLineId"));

                    b.Property<string>("Durations")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("EndHour")
                        .HasColumnType("varchar(10)");

                    b.Property<int?>("LevelId")
                        .HasColumnType("int");

                    b.Property<decimal?>("PricPer")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("RegistrationId")
                        .HasColumnType("int");

                    b.Property<string>("StartHour")
                        .HasColumnType("varchar(10)");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("RegistrationLineId");

                    b.HasIndex("RegistrationId");

                    b.ToTable("RegistrationLines");
                });

            modelBuilder.Entity("SRMS.Shared.Models.Subject", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjectId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Duration")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SubjectCode")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("SubjectId");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("SRMS.Shared.Models.SubjectType", b =>
                {
                    b.Property<int>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TypeId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("TypeId");

                    b.ToTable("SubjectTypes");
                });

            modelBuilder.Entity("SRMS.Shared.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<string>("UserType")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            FullName = "Admin",
                            Image = "",
                            IsActive = false,
                            Password = "123",
                            UserType = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("SRMS.Shared.Models.RegistrationLine", b =>
                {
                    b.HasOne("SRMS.Shared.Models.Registration", "Registration")
                        .WithMany("RegistrationLines")
                        .HasForeignKey("RegistrationId");

                    b.Navigation("Registration");
                });

            modelBuilder.Entity("SRMS.Shared.Models.Registration", b =>
                {
                    b.Navigation("RegistrationLines");
                });
#pragma warning restore 612, 618
        }
    }
}
